//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mb.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Cuentas = new HashSet<Cuenta>();
        }
    
        public int idpedido { get; set; }
        public string UserId { get; set; }
        public int IdMesa { get; set; }
        public int IdMesaUsuario { get; set; }
        public int IdProducto { get; set; }
        public int IdEstado { get; set; }
        public int cantidad { get; set; }
        public float precio { get; set; }
        public Nullable<float> subtotal { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuentas { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
    }
}
