//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mb.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubTipo()
        {
            this.TipoProductoes = new HashSet<TipoProducto>();
        }
    
        public int idSubTipo { get; set; }
        public string descripcion_subtipo { get; set; }
        public string detalle_subtipo { get; set; }
        public System.DateTime fecha_carga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoProducto> TipoProductoes { get; set; }
    }
}
