//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public Cuenta()
        {
            this.Pedidoes = new HashSet<Pedido>();
        }
    
        public int id { get; set; }
        public Nullable<int> idUserMesa { get; set; }
        public int estadoCod { get; set; }
        public string estado_descri { get; set; }
        public System.DateTime fecha { get; set; }
        public bool esactual { get; set; }
        public double total { get; set; }
    
        public virtual UserMesa UserMesa { get; set; }
        public virtual ICollection<Pedido> Pedidoes { get; set; }
    }
}
