//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        public Mesa()
        {
            this.UserMesas = new HashSet<UserMesa>();
        }
    
        public int Id { get; set; }
        public int idqr { get; set; }
        public int numero { get; set; }
        public Nullable<int> cant_silla_aprox { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public bool disponible { get; set; }
    
        public virtual QR QR { get; set; }
        public virtual ICollection<UserMesa> UserMesas { get; set; }
    }
}
