//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int id { get; set; }
        public int IdUserMesa { get; set; }
        public int IdProducto { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public int cantidad { get; set; }
        public float precio { get; set; }
        public double subtotal { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        public virtual UserMesa UserMesa { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
