//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilMesa
    {
        public PerfilMesa()
        {
            this.UserMesas = new HashSet<UserMesa>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string cod { get; set; }
    
        public virtual ICollection<UserMesa> UserMesas { get; set; }
    }
}
