//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QR
    {
        public QR()
        {
            this.Mesas = new HashSet<Mesa>();
        }
    
        public int idqr { get; set; }
        public string texto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> habilitado { get; set; }
    
        public virtual ICollection<Mesa> Mesas { get; set; }
    }
}
